DROP DATABASE IF EXISTS BullsAndCowstest;

CREATE DATABASE IF NOT EXISTS BullsAndCowstest;

USE BullsAndCowstest;

CREATE TABLE IF NOT EXISTS Game (
    GameId INT PRIMARY KEY AUTO_INCREMENT,
    Answer CHAR(4) NOT NULL,
    Finished BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Round (
    RoundId INT PRIMARY KEY AUTO_INCREMENT,
    GameId INT NOT NULL,
    Guess CHAR(4) NOT NULL,
    `Time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Result CHAR(7),
    CONSTRAINT fk_Round_Game FOREIGN KEY (GameId)
        REFERENCES Game (GameId)
);

